DROP TABLE INFO_BOARD;
DROP TABLE DIARY;
DROP TABLE "ACCOUNT_BOOK";

DROP TABLE "ATTACHMENT";
DROP TABLE "LIKE";
DROP TABLE "MARK";

DROP TABLE "RECOMMENT";
DROP TABLE "COMMENT";

DROP TABLE "REVIEW";
DROP TABLE "MY_PROGRAM";
DROP TABLE "PROGRAM";
DROP TABLE "MARKET";

DROP TABLE FARM;
DROP TABLE "BOARD";
DROP TABLE "MEMBER";

--멤버 테이블 수정완료

CREATE TABLE "MEMBER" (
"MEM_NO" NUMBER	NOT NULL PRIMARY KEY,
"MEM_ID"	VARCHAR2(300)		NOT NULL,
"MEM_PWD"	VARCHAR2(300)		NOT NULL,
"NAME"	VARCHAR2(300)		NULL,
"NICKNAME"	VARCHAR2(300)		NULL,
"PHONE"	VARCHAR2(300)		NULL,
"GENDER"	CHAR(1)		NULL,
"EMAIL"	VARCHAR2(300)		NULL,
"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NULL,
"MEM_STATUS"	CHAR(1)	DEFAULT 'Y' NULL CHECK (MEM_STATUS IN('Y', 'N')),
"FARMER_CODE"	VARCHAR2(300)		NULL,
"CAREER" VARCHAR2(300),
"MODIFY_DATE" DATE
);

COMMENT ON COLUMN "MEMBER"."MEM_STATUS" IS '"A" 관리자';
COMMENT ON COLUMN "MEMBER"."FARMER_CODE" IS '있으면 농부 없으면 일반사용자';

DROP SEQUENCE SEQ_MNO;
CREATE SEQUENCE SEQ_MNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999
NOCYCLE
NOCACHE
NOORDER;

--농장 테이블 수정완료

CREATE TABLE FARM (
FARM_NO NUMBER PRIMARY KEY,
FARMER NUMBER NOT NULL,
FARM_NAME VARCHAR2(30) NOT NULL,

FARM_INTRO VARCHAR2(300) NOT NULL,
LOCAL_CODE VARCHAR2(20) NULL,
ADDRESS VARCHAR2(100) NOT NULL,
PHONE	VARCHAR2(20) NOT NULL,
ENROLL_DATE DATE DEFAULT SYSDATE,
STATUS	CHAR(1) DEFAULT 'Y' NULL CHECK (STATUS IN('Y', 'N')),
CROP VARCHAR2(30) NULL
);

COMMENT ON COLUMN FARM.STATUS IS '농장삭제여부(N-삭제)';

DROP SEQUENCE SEQ_FNO;
CREATE SEQUENCE SEQ_FNO;

--정보 게시판 테이블 수정완료

CREATE TABLE INFO_BOARD (
INFO_NO NUMBER PRIMARY KEY,
WRITER	NUMBER	NOT NULL REFERENCES MEMBER(MEM_NO),
CATEGORY VARCHAR2(20) NULL,
INFO_TITLE VARCHAR2(300) NOT NULL,
INFO_CONTENT VARCHAR2(4000) NULL,
SOURCE VARCHAR2(100) NULL,
ENROLL_DATE DATE DEFAULT SYSDATE NULL,
COUNT	NUMBER DEFAULT 0 NULL,
STATUS	CHAR(1)	DEFAULT 'Y' NULL CHECK (STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN INFO_BOARD.STATUS IS '글삭제여부(N-삭제)';

--게시판 테이블 수정 완료
DROP SEQUENCE SEQ_INO;
CREATE SEQUENCE SEQ_INO;

CREATE TABLE "BOARD" (
"BOARD_NO"	NUMBER	PRIMARY KEY,
"BOARD_TYPE"	VARCHAR2(30)		NOT NULL,
"BOARD_TITLE"	VARCHAR2(50)		NOT NULL,
"BOARD_CONTENT"	VARCHAR2(1000)		NOT NULL,
"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
"MODIFY_DATE"	DATE		NULL,
"THUMBNAIL"	VARCHAR2(100)		NULL,
"RECRUIT_YN"	CHAR(1)		NULL,
"COUNT"	NUMBER		NULL,
"STATUS"	CHAR(1)	DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')) NOT NULL,
"MEM_NO"	NUMBER	NOT NULL,
FOREIGN KEY("MEM_NO") REFERENCES MEMBER(MEM_NO)
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS 'SEQUENCE';
COMMENT ON COLUMN "BOARD"."BOARD_TYPE" IS 'S-자랑, Q-질문, K-노하우, M-멘티멘토';
COMMENT ON COLUMN "BOARD"."THUMBNAIL" IS '자랑게시판만 사용';
COMMENT ON COLUMN "BOARD"."RECRUIT_YN" IS '모집중-N, 모집완료-Y';
COMMENT ON COLUMN "BOARD"."STATUS" IS 'CHECK(Y/N)';

DROP SEQUENCE SEQ_BNO;
CREATE SEQUENCE SEQ_BNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999
NOCYCLE
NOCACHE
NOORDER;

--농작물거래테이블 수정완료

CREATE TABLE "MARKET" (
"MARKET_NO"	NUMBER PRIMARY KEY,
"MK_CATEGORY" VARCHAR2(30) NOT NULL,
"MK_TITLE" VARCHAR2(50)	NOT NULL,
"MK_PRICE" NUMBER NULL,
"MK_INTRO" VARCHAR2(100) NULL,
"MK_CONTENT" VARCHAR2(1000)	NULL,
"MK_ENROLLDATE"	DATE DEFAULT SYSDATE NULL,
"MK_COUNT" NUMBER DEFAULT 0 NULL,
"MK_STATUS"	CHAR(2) DEFAULT 'Y' CHECK (MK_STATUS IN('Y', 'N')) NULL,
"MEM_NO" NUMBER NOT NULL,
FOREIGN KEY("MEM_NO") REFERENCES MEMBER(MEM_NO)
);

COMMENT ON COLUMN "MARKET"."MARKET_NO" IS '게시글번호';
COMMENT ON COLUMN "MARKET"."MK_CATEGORY" IS '카테고리(농산물,축산물,수산물)';
COMMENT ON COLUMN "MARKET"."MK_TITLE" IS '제목';
COMMENT ON COLUMN "MARKET"."MK_PRICE" IS '상품가격';
COMMENT ON COLUMN "MARKET"."MK_INTRO" IS '상세조회시사진옆에보여줄소개글';
COMMENT ON COLUMN "MARKET"."MK_CONTENT" IS '상세조회시하단에보여질소개글';
COMMENT ON COLUMN "MARKET"."MK_ENROLLDATE" IS '등록날짜';
COMMENT ON COLUMN "MARKET"."MK_COUNT" IS '조회수';
COMMENT ON COLUMN "MARKET"."MK_STATUS" IS '글삭제여부';

DROP SEQUENCE SEQ_MKNO;

CREATE SEQUENCE SEQ_MKNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999
NOCYCLE
NOCACHE
NOORDER;

--영농일지 테이블 수정완료

CREATE TABLE DIARY(
DIARY_NO NUMBER PRIMARY KEY,
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
CREATE_DATE DATE DEFAULT SYSDATE,
GOODS VARCHAR2(30)  NOT NULL CHECK(GOODS IN('IN', 'OUT')),
DIARY_CONTENT VARCHAR2(1000) NOT NULL,
STATUS CHAR(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')) ,
MEM_NO NUMBER REFERENCES MEMBER(MEM_N[O](https://www.notion.so/_-_0104-8d2c5d607b7c44c19c655b38cf5c79aa)),

DIARY_THUMBNAIL VARCHAR2(300)
);

COMMENT ON COLUMN "DIARY"."DIARY_NO" IS 'SEQUENCE';
COMMENT ON COLUMN "DIARY"."STATUS" IS 'Y/N';

DROP SEQUENCE SEQ_DNO;
CREATE SEQUENCE SEQ_DNO;

--입출금일지 테이블 수정완료

CREATE TABLE "ACCOUNT_BOOK" (
"ACCOUNT_NO"	NUMBER	NOT NULL PRIMARY KEY,
"TYPE"	VARCHAR2(5)		NOT NULL,
"CREATE_DATE"	DATE	DEFAULT SYSDATE,
"TRANSFER_DATE"	DATE		NOT NULL,
"CATEGORY"	VARCHAR2(30)		NOT NULL,
"GOODS"	VARCHAR2(30)		NOT NULL,
"AMOUNT"	NUMBER		NOT NULL,
"CONTENT"	VARCHAR2(1000)		NOT NULL,
"STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
"MEM_NO"	NUMBER REFERENCES MEMBER(MEM_NO)
);

COMMENT ON COLUMN "ACCOUNT_BOOK"."ACCOUNT_NO" IS 'SEQUENCE';
COMMENT ON COLUMN "ACCOUNT_BOOK"."TYPE" IS 'IN/OUT';
COMMENT ON COLUMN "ACCOUNT_BOOK"."STATUS" IS 'Y/N';

DROP SEQUENCE SEQ_ACCNO;
CREATE SEQUENCE SEQ_ACCNO;

--첨부파일 테이블 수정완료

CREATE TABLE "ATTACHMENT" (
"FILE_NO" NUMBER PRIMARY KEY,
"ORIGIN_NAME" VARCHAR2(100)	NULL,
"CHANGE_NAME" VARCHAR2(100)	NULL,
"FILE_PATH"	VARCHAR2(100) NULL,
"UPLOAD_DATE" DATE DEFAULT SYSDATE NULL,
"BOARD_NO" NUMBER NULL,
"BOARD_TYPE" VARCHAR2(30) NULL
);

COMMENT ON COLUMN "ATTACHMENT"."FILE_NO" IS '첨부파일번호';
COMMENT ON COLUMN "ATTACHMENT"."BOARD_TYPE" IS 'S자랑,Q질문,K노하우,M멘티멘토,T거래,P프로그램,A가계부,D일기,F농장';

DROP SEQUENCE SEQ_ANO;
CREATE SEQUENCE SEQ_ANO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999
NOCYCLE
NOCACHE
NOORDER;

--프로그램 테이블 완료

CREATE TABLE "PROGRAM" (
"PROGRAM_NO" NUMBER	 PRIMARY KEY NOT NULL,
"FARM_NO"	NUMBER	NOT NULL,
"PROGRAM_NAME"	VARCHAR2(100)	NOT NULL,
"PROGRAM_PLAN"	DATE	NOT NULL,
"PROGRAM_HOUR"	VARCHAR2(30)	NOT NULL,
"PROGRAM_LECTURE" VARCHAR2(30)	NOT NULL,
"HEADCOUNT"	NUMBER	NOT NULL,
"PROGRAM_DETAIL"	VARCHAR2(30)	NOT NULL,
"SIGN_UP"	VARCHAR2(5)		NOT NULL,
"MEM_NO" NUMBER NOT NULL,
"ORIGIN_NAME" VARCHAR2(4000),
"CHANGE_NAME" VARCHAR2(4000),
"PROGRAM_LOCATION" VARCHAR2(50),
FOREIGN KEY("MEM_NO") REFERENCES MEMBER(MEM_NO),
FOREIGN KEY("FARM_NO") REFERENCES FARM(FARM_NO)
);

DROP SEQUENCE SEQ_PNO;
CREATE SEQUENCE SEQ_PNO;

--참여프로그램 테이블 완료

CREATE TABLE "MY_PROGRAM" (
"PROGRAM_NO" NUMBER	NOT NULL,
"MEM_NO" NUMBER	NOT NULL,
FOREIGN KEY("PROGRAM_NO") REFERENCES PROGRAM("PROGRAM_NO"),
FOREIGN KEY("MEM_NO") REFERENCES MEMBER(MEM_NO)
);

--리뷰 테이블 완료

CREATE TABLE "REVIEW" (
"REVIEW_NO"	NUMBER PRIMARY KEY	NOT NULL,
"REVIEW_COUNT"	NUMBER	NOT NULL,
"REVIEW_CONTENT"	VARCHAR2(1000)	NOT NULL,
"REVIEW_STATUS"	VARCHAR2(5)	DEFAULT 'Y'	NOT NULL,
"REVIEW_ENROLLDATE"	DATE	DEFAULT SYSDATE	NULL,
"PROGRAM_NO" NUMBER NOT NULL,
"MEM_NO" NUMBER NOT NULL,
FOREIGN KEY("PROGRAM_NO") REFERENCES PROGRAM("PROGRAM_NO"),
FOREIGN KEY("MEM_NO") REFERENCES MEMBER("MEM_NO")
);

DROP SEQUENCE SEQ_RVNO;
CREATE SEQUENCE SEQ_RVNO;

--좋아요 테이블 수정완료

CREATE TABLE "LIKE" (
"MEM_NO"	NUMBER	NOT NULL REFERENCES MEMBER(MEM_NO),
"STATUS"	NUMBER	NULL CHECK (STATUS IN('0', '1')),
"BOARD_TYPE"	VARCHAR2(30) NULL,
"BOARD_NO"	NUMBER NULL
);

COMMENT ON COLUMN "LIKE"."MEM_NO" IS '회원번호';
COMMENT ON COLUMN "LIKE"."STATUS" IS '취소여부 (누르면1 취소하면 0)';
COMMENT ON COLUMN "LIKE"."BOARD_TYPE" IS 'S-자랑, Q-질문, K-노하우, M-멘티멘토';

--찜하기테이블 수정완료

CREATE TABLE "MARK" (
"MEM_NO" NUMBER	NOT NULL,
"STATUS" NUMBER	NULL,
"BOARD_TYPE" VARCHAR2(30) NULL,
"BOARD_NO" NUMBER NULL,
FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO)
);

COMMENT ON COLUMN "MARK"."MEM_NO" IS '회원번호';
COMMENT ON COLUMN "MARK"."STATUS" IS '취소여부 (누르면 1 취소하면 0)';
COMMENT ON COLUMN "MARK"."BOARD_TYPE" IS 'T-거래, P-프로그램';

DROP SEQUENCE SEQ_MARKNO;
CREATE SEQUENCE SEQ_MARKNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999
NOCYCLE
NOCACHE
NOORDER;

--댓글 테이블 수정완료

CREATE TABLE "COMMENT" (
"COMMENT_NO" NUMBER	NOT NULL PRIMARY KEY,
"COMMENT_CONTENT"	VARCHAR2(300)		NOT NULL,
"COMMENT_DATE"	DATE	NULL,
"BOARD_TYPE"	VARCHAR2(30)		NULL,
"BOARD_NO"	NUMBER	NOT NULL,
FOREIGN KEY("BOARD_NO") REFERENCES BOARD(BOARD_NO)
);

-- 댓글 시퀀스
DROP SEQUENCE SEQ_CNO;
CREATE SEQUENCE SEQ_CNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999
NOCYCLE
NOCACHE
NOORDER;

--대댓글 테이블 수정완료

CREATE TABLE "RECOMMENT" (
"RECOMMENT_NO"	NUMBER	NOT NULL PRIMARY KEY,
"RECOMMENT_CONTENT"	VARCHAR2(300) NOT NULL,
"RECOMMENT_DATE"	DATE	NULL,
"COMMENT_NO"	NUMBER	NOT NULL,
FOREIGN KEY ("COMMENT_NO") REFERENCES "COMMENT"(COMMENT_NO)
);

-- 대댓글 시퀀스
DROP SEQUENCE SEQ_RCNO;
CREATE SEQUENCE SEQ_RCNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999
NOCYCLE
NOCACHE
NOORDER;